/* Generated by x1_llm_compiler.weight_image; expanded for large-DMA RTL coverage. */
#ifndef X1_REAL_WEIGHT_FIRMWARE_VECTOR_H
#define X1_REAL_WEIGHT_FIRMWARE_VECTOR_H

#include <stdint.h>

#define X1_REAL_QUEUE_BASE 0x10000000u
#define X1_REAL_WEIGHT_BASE 0x80000000u
#define X1_REAL_RESULT_SRAM_BASE 0x00002000u
#define X1_REAL_RESULT_PERIPH_BASE 0x90000000u
#define X1_REAL_WINDOW_WORDS 32u
#define X1_REAL_DESCRIPTOR_WORDS 16u
#define X1_REAL_DESCRIPTOR_COUNT 5u
#define X1_REAL_NUM_MACROS 4u
#define X1_REAL_ROW 1u
#define X1_REAL_COL 11u
#define X1_REAL_ROLE_ID 3u
#define X1_REAL_BITS_PER_VALUE 9u
#define X1_REAL_COARSE_BITS 5u
#define X1_REAL_FINE_BITS 3u
#define X1_REAL_VC 1u
#define X1_REAL_DST 3u
#define X1_REAL_TILE_GROUP 0u
#define X1_REAL_EXPECTED_HEADER_HI 0x134D6001u
#define X1_REAL_EXPECTED_HEADER_LO 0x0000E400u
#define X1_REAL_OP_DMA_LOAD 1u
#define X1_REAL_OP_DMA_STORE 2u
#define X1_REAL_OP_PROGRAM_X1_WINDOW 3u
#define X1_REAL_OP_EXECUTE_TILE 4u
#define X1_REAL_OP_NOC_SEND 5u

/* model.layers.0.self_attn.q_proj.weight from ../e_drive_dma_artifacts/e_qwen_l0_qproj_tile00.u32.bin. */
/* Firmware uses only the addresses/ops below; descriptor and weight data are DMA-served. */
static const uint32_t x1_real_expected_ops[5] = {
    1u, 3u, 4u, 5u, 2u
};

static const uint32_t x1_real_expected_results[5] = {
    32u, 32u, 0u, 4u, 4u
};

static const uint32_t x1_real_expected_payload[4] = {
    102u, 4u, 0u, 0u
};

#endif
